### ISSUE TITLE
перевод на русский язык

### ISSUE THREAD

**Issue by beyudn** [atc-project/atc-react#280]
предлагаю перевести RA на русский язык и создать параллельную ветку.

**Comment by yugoslavskiy** [comment]
привет @beyudn! 

## Комментарии к твоему предложению

я думаю параллельная ветка все же не лучшее решение, потому что:

- придется поддерживать две ветки вместо одной, сложно будет синкать код для скриптов которые процессят все это дело. с этим нужно будет работать людям, а людей у нас как раз **очень** мало (если быть точнее, людей со свободным временем и желанием этим заниматься)
- сложно будет сходу понять что есть русская версия, нужно будет переключаться куда-то при скачивании проекта
- и наверное много других подводных камней, о которых еще предстоит узнать когда мы пойдем этим путем

## Встречное предложение

на мой взгляд будет логичнее держать русскую версию в тех же документах. YAML поддерживает возможность создания нескольких документов в одном файле. Это делают ребята из Sigma, Atomic Red Team, и наверное много кто еще. Работает это следующим образом:

```yaml
поле: значение
---
поле: значение
---
поле: значение
```

Собственно, в первом документе может быть английская версия, во втором — русская. 
мы можем отделно создать поле с определением языка. типо:

```yaml
lang: EN
title: RA_1001_practice
id: RA1001
description: Practice in the real environment. Sharpen Response Actions within your organization
author: '@atc_project'
creation_date: 08.04.2020
stage: preparation
workflow: |
  Make sure that most of the Response Action has been performed on an internal exercise by your Incident Response Team.  
  You need to make sure that when an Incident will happen, the team will not just try to follow the playbooks they see first time in their lives, but will be able to quickly execute the actual steps in **your environment**, i.e. blocking an IP address or a domain name.  
---
lang: RU
title: RA_1001_практика
id: RA1001
description: Практикуйтесь в реальном окружении. Оттачивайте Действия Реагирования в своей организации
author: '@atc_project (оригинал), @beyudn (перевод)
creation_date: 14.05.2020
stage: preparation
workflow: |
  Убедитесь в том что вы можете то се
```

Соответственно, все это дело всегда будет в основной ветке. Мешать никому оно не будет. Места оно практически не занимает. 

## Как оно будет обрабатываться

Все работает следующим образом. 

1. Yaml файл парсится
2. В памяти происходит обогащение (нормализуются имена, добавляются категории, линкуются разные другие аналитики)
3. Когда объект обогащен и нормализован, оно отдается jinja, и посредством [шаблонов](https://github.com/atc-project/atc-react/tree/master/scripts/templates) превращается в markdown файлы и базу знаний mkdocs
4. Далее это дело экспортируется в разные системы 

## Что нужно сделать чтобы все заработало

1. Внедрить поле с определением языка в RA, RP и RS
2. Разработать русскоязычные документы в тех же YAML файлах
3. Добавить в парсер логику для разделения доков по языкам
4. Добавить в `main.py` опцию с выбором языка
5. Создать шаблоны jinja для русскоязычных документов
6. Придумать как (куда) экспортировать русскую версию (тут наверное будет просто полное зеркало всех ресурсов, чисто под русский язык)

В общем-то, как-то так. Осталось найти единомышленников, готовых вписаться, @beyudn .
